apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilleggsstonader-soknad-api
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader

spec:
  port: 8080
  image: {{ image }}
  ingresses:
    - https://tilleggsstonader-soknad-api.intern.dev.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: false
        pointInTimeRecovery: false
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: tilleggsstonader-soknad
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-soknad
        - application: tilleggsstonader-prosessering
    outbound:
      external:
        - host: pdl-api-q1.dev-fss-pub.nais.io
  tokenx:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev

