apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilleggsstonader-soknad-api
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader

spec:
  port: 8080
  image: {{ image }}
  ingresses:
    - https://tilleggsstonader-soknad-api.intern.dev.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
      cpu: 500m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: false
        pointInTimeRecovery: false
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: tilleggsstonader-soknad
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-soknad
        - application: tilleggsstonader-prosessering
    outbound:
      rules:
        - application: tilleggsstonader-integrasjoner
        - application: tilleggsstonader-htmlify
        - application: tilleggsstonader-sak
        - application: familie-dokument
          namespace: teamfamilie
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: kodeverk-api.nav.no
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS gir alle tilgang i preprod til prosessering
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev

