apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilleggsstonader-soknad-api
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader

spec:
  port: 8080
  image: {{ image }}
  ingresses:
    - https://tilleggsstonader-soknad-api.intern.nav.no
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 1Gi # Lik requests som beste praksis
    requests:
      memory: 1Gi
      cpu: 50m
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: tilleggsstonader-soknad
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-soknad
        - application: tilleggsstonader-prosessering
    outbound:
      rules:
        - application: tilleggsstonader-integrasjoner
        - application: tilleggsstonader-htmlify
        - application: tilleggsstonader-sak
        - application: familie-dokument
          namespace: teamfamilie
        - application: kodeverk-api
          namespace: team-rocket
        - application: logging
          namespace: nais-system
      external:
        - host: pdl-api.prod-fss-pub.nais.io
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "9f2c914f-9619-41a2-bea6-d62910514c8a" # Team Tilleggsstønader - Utviklere # tilgang ti prosessering
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: TZ
      value: Europe/Oslo
