prosessering:
  rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS gir alle tilgang i preprod til prosessering

CLIENT_ENV: dev
clients:
  pdl:
    uri: https://pdl-api-q1.dev-fss-pub.nais.io
    audience: dev-fss:pdl:pdl-api-q1
    scope: api://dev-fss.pdl.pdl-api-q1/.default