name: Bygg og deploy til prod og dev

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_deploy:
    name: "Bygger app og deployer til prod og dev"
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-deploy-prod-and-dev.yml@main
    secrets: inherit
    permissions:
      contents: "write" # Kreves av nais/login
      id-token: "write" # Kreves for 책 skrive s책rbarhetsanalyse-rapport
      security-events: "write" # Kreves for 책 pushe resultat av s책rbarhetsanalyse til Github Security
    with:
      prod-cluster: 'prod-gcp'
      prod-manifest: '.nais/prod.yaml'
      dev-cluster: 'dev-gcp'
      dev-manifest: '.nais/preprod.yaml'
