name: Build, push, and deploy app to dev and prod

on:
  push:
    branches:
      - 'main'

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    name: Build, push and deploy to dev-gcp and prod-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Test and build
        run: ./gradlew test bootJar -PskipLint

      - name: Generate and output SBOM
        run: ./gradlew cyclonedxBom

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: tilleggsstonader
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          byosbom: build/reports/bom.json

      - name: Post build failures to Slack
        if: failure()
        run: |
          curl -X POST --data "{\"text\": \"Build av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
    name: Deploy to GCP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/preprod.yaml
          IMAGE: ${{ needs.build.outputs.image }}

      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}

      - name: Post deploy failures to Slack
        if: failure()
        run: |
          curl -X POST --data "{\"text\": \"Deploy av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          MESSAGE: "Deploy av feilet"
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
