name: Submit dependency graph
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
      - "gradle.properties"
      - ".github/workflows/submit-dependency-graph.yaml"
jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit

      - name: Run a build (dependency-graph will be generated and submitted post-job)
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        run: ./gradlew --configuration-cache build -x :check -x :cyclonedxBom