name: Send inn avhengighetsgraf til GitHub Security

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
      - "gradle.properties"

jobs:
  submit-dependency-graph:
    name: "Genererer opp avhengighetsgraf og sender den til GHAS"
    uses: navikt/tilleggsstonader/.github/workflows/submit-dependency-graph.yml@main
    permissions:
      contents: "write" # Kreves av Dependency Submission API-et
